name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Global Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Prepare missing files and Keystore
      run: |
        # 创建缺失的隐藏环境变量文件
        touch .env.example
        touch .env
        
        # 将 base64 文本格式的签名还原成真正的二进制密钥库文件
        base64 -d debug.keystore.base64 > debug.keystore

    - name: Build debug APK
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: "app/build/outputs/apk/debug/**/*.apk"
