name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Auto-detect and Build
      run: |
        # 让服务器自动搜索 gradlew 文件所在的文件夹，并自动进入该文件夹
        cd $(dirname $(find . -name gradlew | head -n 1))
        
        # 赋予权限并执行打包
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        # 使用通配符，在任何层级的目录下自动抓取生成的 apk 文件
        path: "**/app/build/outputs/apk/debug/**/*.apk"
