name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Global Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build debug APK
      # 因为你的文件全在最外层，且使用的是 .kts，直接在此处呼叫全局 gradle 即可
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        # 抓取 app 文件夹下生成的 apk 文件
        path: "app/build/outputs/apk/debug/**/*.apk"
